# Sets the base of all pull requests to the "staging" branch: the main branch
# should not have material changes to it between releases.

name: Set Base
on: [pull_request]

jobs:
  label:

    runs-on: ubuntu-latest

  check-base-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: a-b-r-o-w-n/check-base-branch-action@v1.1
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          protected-branches: "master"
          default-branch: "staging"
          update-branch: true
